// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trafficshaper

import "github.com/browningluke/opnsense-go/pkg/api"

const trafficshaperReconfigureEndpoint = "/trafficshaper/service/reconfigure"

// Controller for trafficshaper
type Controller struct {
	Api *api.Client
}

func (c *Controller) Client() *api.Client {
	return c.Api
}
