// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trafficshaper

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var PipeOpts = api.ReqOpts{
	AddEndpoint:         "/trafficshaper/settings/addPipe",
	GetEndpoint:         "/trafficshaper/settings/getPipe",
	UpdateEndpoint:      "/trafficshaper/settings/setPipe",
	DeleteEndpoint:      "/trafficshaper/settings/delPipe",
	ReconfigureEndpoint: trafficshaperReconfigureEndpoint,
	Monad:               "pipe",
}

// Data structs

type Pipe struct {
	Number          string          `json:"number"`
	Enabled         string          `json:"enabled"`
	Bandwidth       string          `json:"bandwidth"`
	BandwidthMetric api.SelectedMap `json:"bandwidthMetric"`
	Queue           string          `json:"queue"`
	Mask            api.SelectedMap `json:"mask"`
	Buckets         string          `json:"buckets"`
	Scheduler       api.SelectedMap `json:"scheduler"`
	CoDelEnable     string          `json:"codel_enable"`
	CoDelTarget     string          `json:"codel_target"`
	CoDelInterval   string          `json:"codel_interval"`
	CoDelECNEnable  string          `json:"codel_ecn_enable"`
	PIEEnable       string          `json:"pie_enable"`
	FQCoDelQuantum  string          `json:"fqcodel_quantum"`
	FQCoDelLimit    string          `json:"fqcodel_limit"`
	FQCoDelFlows    string          `json:"fqcodel_flows"`
	Origin          string          `json:"origin"`
	Delay           string          `json:"delay"`
	Description     string          `json:"description"`
}

// CRUD operations

func (c *Controller) AddPipe(ctx context.Context, resource *Pipe) (string, error) {
	return api.Add(c.Client(), ctx, PipeOpts, resource)
}

func (c *Controller) GetPipe(ctx context.Context, id string) (*Pipe, error) {
	return api.Get(c.Client(), ctx, PipeOpts, &Pipe{}, id)
}

func (c *Controller) UpdatePipe(ctx context.Context, id string, resource *Pipe) error {
	return api.Update(c.Client(), ctx, PipeOpts, resource, id)
}

func (c *Controller) DeletePipe(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, PipeOpts, id)
}
