// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trafficshaper

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var QueueOpts = api.ReqOpts{
	AddEndpoint:         "/trafficshaper/settings/addQueue",
	GetEndpoint:         "/trafficshaper/settings/getQueue",
	UpdateEndpoint:      "/trafficshaper/settings/setQueue",
	DeleteEndpoint:      "/trafficshaper/settings/delQueue",
	ReconfigureEndpoint: trafficshaperReconfigureEndpoint,
	Monad:               "queue",
}

// Data structs

type Queue struct {
	Number         string          `json:"number"`
	Enabled        string          `json:"enabled"`
	Pipe           api.SelectedMap `json:"pipe"`
	Weight         string          `json:"weight"`
	Mask           api.SelectedMap `json:"mask"`
	Buckets        string          `json:"buckets"`
	CoDelEnable    string          `json:"codel_enable"`
	CoDelTarget    string          `json:"codel_target"`
	CoDelInterval  string          `json:"codel_interval"`
	CoDelECNEnable string          `json:"codel_ecn_enable"`
	PIEEnable      string          `json:"pie_enable"`
	Description    string          `json:"description"`
	Origin         string          `json:"origin"`
}

// CRUD operations

func (c *Controller) AddQueue(ctx context.Context, resource *Queue) (string, error) {
	return api.Add(c.Client(), ctx, QueueOpts, resource)
}

func (c *Controller) GetQueue(ctx context.Context, id string) (*Queue, error) {
	return api.Get(c.Client(), ctx, QueueOpts, &Queue{}, id)
}

func (c *Controller) UpdateQueue(ctx context.Context, id string, resource *Queue) error {
	return api.Update(c.Client(), ctx, QueueOpts, resource, id)
}

func (c *Controller) DeleteQueue(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, QueueOpts, id)
}
