// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package trafficshaper

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/api"
)

var RuleOpts = api.ReqOpts{
	AddEndpoint:         "/trafficshaper/settings/addRule",
	GetEndpoint:         "/trafficshaper/settings/getRule",
	UpdateEndpoint:      "/trafficshaper/settings/setRule",
	DeleteEndpoint:      "/trafficshaper/settings/delRule",
	ReconfigureEndpoint: trafficshaperReconfigureEndpoint,
	Monad:               "rule",
}

// Data structs

type Rule struct {
	Enabled         string              `json:"enabled"`
	Sequence        string              `json:"sequence"`
	Interface       api.SelectedMap     `json:"interface"`
	Interface2      api.SelectedMap     `json:"interface2"`
	Protocol        api.SelectedMap     `json:"proto"`
	IPLength        string              `json:"iplen"`
	Source          api.SelectedMapList `json:"source"`
	SourceNot       string              `json:"source_not"`
	SourcePort      string              `json:"src_port"`
	Destination     api.SelectedMapList `json:"destination"`
	DestinationNot  string              `json:"destination_not"`
	DestinationPort string              `json:"dst_port"`
	DSCP            api.SelectedMapList `json:"dscp"`
	Direction       api.SelectedMap     `json:"direction"`
	Target          api.SelectedMap     `json:"target"`
	Description     string              `json:"description"`
	Origin          string              `json:"origin"`
}

// CRUD operations

func (c *Controller) AddRule(ctx context.Context, resource *Rule) (string, error) {
	return api.Add(c.Client(), ctx, RuleOpts, resource)
}

func (c *Controller) GetRule(ctx context.Context, id string) (*Rule, error) {
	return api.Get(c.Client(), ctx, RuleOpts, &Rule{}, id)
}

func (c *Controller) UpdateRule(ctx context.Context, id string, resource *Rule) error {
	return api.Update(c.Client(), ctx, RuleOpts, resource, id)
}

func (c *Controller) DeleteRule(ctx context.Context, id string) error {
	return api.Delete(c.Client(), ctx, RuleOpts, id)
}
